const {launcher}=require('miniprogram-automator')
const pause=ms=>new Promise(r=>setTimeout(r,ms))
;(async()=>{const mp=await launcher.connectTool({wsEndpoint:'ws://127.0.0.1:9450'});try{
 await mp.reLaunch('/pages/M51/index?member=995055&shop=992051');await pause(1200)
 let p=await mp.currentPage(),root=(await p.$$(' *'.trim()))[1];console.log('start',p.path)
 await(await root.$('input[aria-label="接收人手机号"]')).input('13800005055')
 await(await root.$('input[aria-label="转赠积分"]')).input('10')
 await(await root.$('.bottom-bar button')).tap();await pause(1500)
 p=await mp.currentPage();root=(await p.$$(' *'.trim()))[1];console.log('self',p.path,(await root.outerWxml()).includes('13800005055'))
 await(await root.$('input[aria-label="接收人手机号"]')).input('13800005056')
 await(await root.$('input[aria-label="转赠积分"]')).input('99999')
 await(await root.$('.bottom-bar button')).tap();await pause(1500)
 p=await mp.currentPage();root=(await p.$$(' *'.trim()))[1];console.log('over',p.path,(await root.outerWxml()).includes('99999'))
 console.log('points',await mp.evaluate(()=>{let b=require('data/backend.js').backend;return{member:b.member?.id,platform:b.account?.platformPoints?.available,shop:b.account?.shopPoints?.available}}))
}finally{await mp.disconnect()}})().catch(e=>{console.error(e);process.exitCode=1})
