<template>
  <view v-if="block.type==='notice'" :class="['notice',block.tone]"><Icon :name="block.tone==='orange'?'alert':'shield'" :size="18"/><view><text class="notice-title">{{block.title}}</text><text class="notice-body">{{block.body}}</text></view></view>
  <view v-else-if="block.type==='hero'" class="hero-card"><Photo :asset="block.asset"/><view class="hero-shade"/><view class="hero-copy"><text class="eyebrow">HEXU · QUALITY LIFE</text><text class="hero-title">{{block.title}}</text><text class="hero-subtitle">{{block.subtitle}}</text></view></view>
  <view v-else-if="block.type==='stats'" :class="['stats',{'stats-dark':block.dark}]" :style="{gridTemplateColumns:'repeat('+Math.min(block.items.length,block.items.length===4?2:3)+',1fr)'}"><view v-for="item in block.items" :key="item.label"><text class="stat-value">{{item.value}}</text><text class="stat-label">{{item.label}}</text></view></view>
  <view v-else-if="block.type==='rows'" class="card"><text v-if="block.title" class="section-title">{{block.title}}</text><view v-for="(item,i) in block.items" :key="i" :class="['info-row',{'is-link':item.target}]" @tap="item.target&&$emit('action',item.target)"><text class="row-label">{{item.label}}</text><text class="row-value">{{item.value}}</text><Icon v-if="item.target" name="chevron" :size="16"/></view></view>
  <view v-else-if="block.type==='fields'" class="card form-card"><text v-if="block.title" class="section-title">{{block.title}}</text><view v-for="item in block.items" :key="item.key" :class="['field',{'field-textarea':item.kind==='textarea'}]"><view class="field-label">{{item.label}}<text v-if="item.required" class="required"> *</text></view><switch v-if="item.kind==='switch'" :checked="!!form[item.key]" color="#155641" @change="set(item.key,$event.detail.value)"/><picker v-else-if="item.kind==='select'" :range="item.options||[]" :value="Math.max(0,(item.options||[]).indexOf(form[item.key]))" @change="set(item.key,item.options[$event.detail.value])"><view class="picker-value">{{form[item.key]||'请选择'}} <Icon name="chevron" :size="14"/></view></picker><picker v-else-if="item.kind==='date'" mode="date" :value="form[item.key]" @change="set(item.key,$event.detail.value)"><view class="picker-value">{{form[item.key]}} <Icon name="chevron" :size="14"/></view></picker><view v-else-if="item.kind==='stepper'" class="stepper"><button aria-label="减少数量" @tap="set(item.key,Math.max(1,Number(form[item.key])-1))">−</button><input :value="form[item.key]" type="number" @input="set(item.key,Math.max(1,Number($event.detail.value)))"/><button aria-label="增加数量" @tap="set(item.key,Number(form[item.key]||1)+1)">+</button></view><text v-else-if="item.kind==='readonly'" class="muted">{{form[item.key]}}</text><textarea v-else-if="item.kind==='textarea'" :value="form[item.key]" :placeholder="'请输入'+item.label" maxlength="500" @input="set(item.key,$event.detail.value)"/><input v-else :value="form[item.key]" :type="item.kind==='number'?'digit':'text'" :placeholder="'请输入'+item.label" :aria-label="item.label" @input="set(item.key,$event.detail.value)"/></view></view>
  <view v-else-if="block.type==='product'" class="card product-line" @tap="$emit('action',block.target||'product:'+prod.id)"><view class="product-thumb"><Photo :asset="prod.asset"/></view><view class="product-copy"><text class="product-name">{{block.name||prod.name}}</text><text class="muted small">{{prod.spec||prod.desc}}</text><view class="spread"><text class="price">{{String(block.price||'').includes('积分')?'':'¥'}}{{block.price||money(prod.price)}}</text><text class="muted small">×{{block.qty||1}}</text></view></view></view>
  <view v-else-if="block.type==='links'" class="card quick-links" :style="{gridTemplateColumns:'repeat('+Math.min(block.items.length,4)+',1fr)'}"><button v-for="item in block.items" :key="item.title" @tap="$emit('action',item.target)"><view class="icon-tile"><Icon :name="item.icon" :size="25"/></view><text>{{item.title}}</text></button></view>
  <scroll-view v-else-if="block.type==='tabs'" scroll-x class="tabs-scroll"><view class="tabs"><button v-for="(item,i) in block.items" :key="item" :class="{active:tab===i}" @tap="tab=i;$emit('filter',item)">{{item}}</button></view></scroll-view>
  <view v-else-if="block.type==='search'" class="search-bar"><Icon name="search" :size="18"/><input v-model="query" :placeholder="block.placeholder" @input="$emit('search',query)"/><button v-if="query" @tap="query='';$emit('search','')">×</button></view>
  <view v-else-if="block.type==='timeline'" class="card timeline"><view v-for="(item,i) in block.items" :key="i" :class="['timeline-item',{current:i===block.active,done:i<block.active}]"><view class="timeline-dot"><text v-if="i<block.active">✓</text></view><view><text>{{item.split(' · ')[0]}}</text><text v-if="item.includes(' · ')" class="muted small">{{item.split(' · ').slice(1).join(' · ')}}</text></view></view></view>
  <view v-else-if="block.type==='upload'" class="card"><text class="section-title">{{block.title}}</text><view class="uploads"><view v-for="(file,i) in uploads" :key="i" class="upload-thumb" @tap="removeUpload(i)"><Photo :asset="file"/></view><button class="upload-button" @tap="choose"><Icon name="camera" :size="28"/><text>点击上传</text></button></view><text class="muted tiny">支持 JPG、PNG，最多9张</text></view>
  <view v-else-if="block.type==='options'" class="card option-list"><button v-for="item in block.items" :key="item" :class="{selected:(form[block.key]||block.items[0])===item}" @tap="set(block.key,item)"><text>{{item}}</text><view class="radio">{{(form[block.key]||block.items[0])===item?'✓':''}}</view></button></view>
  <view v-else-if="block.type==='profile'" :class="['profile-card',{dark:block.dark}]"><view class="avatar"><Photo asset="avatar" :radius="50"/></view><view><text class="profile-name">{{block.name}}</text><text class="small">{{block.subtitle}}</text></view></view>
  <view v-else-if="block.type==='consent'" class="consent" @tap="set(block.key,!form[block.key])"><view :class="['checkbox',{checked:form[block.key]}]">{{form[block.key]?'✓':''}}</view><text>{{block.label}}</text></view>
  <view v-else-if="block.type==='checklist'" class="card"><view v-for="(item,i) in block.items" :key="item" class="check-row" @tap="set('check'+i,!form['check'+i])"><view :class="['checkbox',{checked:form['check'+i]}]">{{form['check'+i]?'✓':''}}</view><text>{{item}}</text></view></view>
  <view v-else-if="block.type==='success'" class="success-card"><view class="success-icon"><Icon :name="block.icon||'check'" :size="42" color="white"/></view><text class="success-title">{{block.title}}</text><text v-if="block.value" class="success-value">{{block.value}}</text><text class="muted">{{block.body}}</text></view>
  <view v-else-if="block.type==='amount'" class="amount-card"><text class="muted">{{block.label}}</text><text class="amount-number"><text class="currency">¥</text>{{block.value}}</text></view>
  <view v-else-if="block.type==='rating'" class="card"><text class="section-title">商品评分</text><view class="rating"><button v-for="i in 5" :key="i" :class="{gold:i<=(form.rating||5)}" @tap="set('rating',i)">★</button><text class="muted">{{form.rating||5}}分 满意</text></view></view>
  <view v-else-if="block.type==='reviews'" class="card"><view v-for="(review,i) in backend.reviews" :key="i" class="review"><view class="spread"><text>{{review.name}}</text><text class="gold">{{'★'.repeat(Number(review.rating)||0)}}</text></view><text class="muted tiny">{{review.createdAt}}</text><text>{{review.content}}</text></view><text v-if="!backend.reviews.length" class="muted small">暂无已审核评价</text></view>
  <view v-else-if="block.type==='chart'" class="card"><view class="spread"><text class="section-title">{{block.title}}</text><text class="muted tiny">{{block.periodLabel||(block.values.length===7?'近7天':'本期')}}</text></view><view class="chart"><view class="chart-grid"/><view v-for="(value,i) in block.values" :key="i" class="chart-column"><view class="bar" :style="{height:value+'%'}"><text>{{block.actualValues?.[i]??value}}</text></view><text class="chart-label">{{block.labels?.[i]||(''+(i+1)+(block.values.length===7?'日':'月'))}}</text></view></view></view>
  <view v-else-if="block.type==='progress'" class="card"><text class="section-title">考核指标</text><view v-for="item in block.items" :key="item[0]" class="progress-item"><view class="spread"><text>{{item[0]}}</text><text class="green">{{item[1]}}</text></view><view class="progress-track"><view :style="{width:item[2]+'%'}"/></view><text class="tiny green">{{item[2]>=100?'已达标':'继续努力'}}</text></view></view>
  <view v-else-if="block.type==='relation'" class="card relation"><view v-for="(item,i) in block.items" :key="item"><view class="relation-node"><Icon :name="i===0?'shop':'user'"/><text>{{item}}</text></view><view v-if="i<block.items.length-1" class="relation-arrow">↓</view></view></view>
  <view v-else-if="block.type==='people'" class="card"><view v-for="(item,i) in visibleItems" :key="item[0]" class="person" @tap="(item[4]||block.target)&&$emit('action',item[4]||block.target)"><view :class="['initial','initial-'+i%3]">{{item[0].slice(0,1)}}</view><view class="flex-one"><view class="spread"><text class="bold">{{item[0]}}</text><text class="bold">{{item[2]}}</text></view><view class="spread"><text class="badge">{{item[1]}}</text><text class="muted tiny">{{item[3]}}</text></view></view></view></view>
  <view v-else-if="block.type==='ledger'" class="card"><view v-for="(item,i) in visibleItems" :key="item[0]+'-'+item[1]+'-'+i" class="ledger-row" @tap="item[3]&&$emit('action',item[3])"><view><text>{{item[0]}}</text><text class="muted tiny">{{item[1]}}</text></view><text :class="['ledger-value',(item[2].startsWith('−')||item[2].startsWith('-'))?'red':'green']">{{item[2]}}</text></view></view>
  <view v-else-if="['productGrid','pointsProducts','productList','stock'].includes(block.type)" :class="['products',{'product-list':block.type==='productList'||block.type==='stock'}]"><view v-for="p in visibleProducts" :key="p.id" class="product-card" @tap="$emit('action',block.productAction?block.productAction+p.id:block.target||(block.type==='pointsProducts'?'points-product:'+p.id:block.type==='stock'?'stock-product:'+p.id:'product:'+p.id))"><view class="goods-photo"><Photo :asset="p.asset"/></view><view class="goods-info"><text class="product-name">{{p.name}}</text><text class="muted tiny">{{block.type==='stock'?'SKU HX-'+p.id.toUpperCase():p.desc}}</text><view class="spread"><text class="price">{{block.type==='pointsProducts'?p.point_price+'积分':block.type==='stock'?'可售 '+p.stock:'¥'+money(p.price)}}</text><text class="badge">{{block.type==='stock'?(p.stock<50?'库存预警':'充足'):'精选'}}</text></view></view></view></view>
  <view v-else-if="block.type==='shops'" class="shop-list"><view v-for="shop in backend.shops" :key="shop.id" class="card" @tap="$emit('action',block.management?'G05':'switch-shop:'+shop.name)"><view class="shop-heading"><view class="shop-icon"><Icon name="shop" :size="28"/></view><view class="flex-one"><text class="bold">{{shop.name}}</text><text class="small muted">{{shop.kind==='DIRECT'?'公司直营':'经销商商城'}} · {{shop.status==='ACTIVE'?'正常经营':shop.status}}</text></view><Icon name="chevron" :size="18"/></view><text class="small muted">{{shop.county}}</text><view class="spread"><text class="badge">{{shop.id===backend.shopId?'我的商城':'独立商城'}}</text><text class="green small">{{block.management?'查看详情':'进入商城'}} →</text></view></view></view>
  <view v-else-if="block.type==='coupons'" class="coupons"><view v-for="(coupon,i) in coupons" :key="i" :class="['coupon',{unavailable:Number(coupon.body.expiresAt)<Date.now()}]" @tap="selectCoupon(i)"><view class="coupon-amount"><text><text class="small">{{coupon.body.type==='DISCOUNT'?'':'¥'}}</text>{{coupon.body.type==='DISCOUNT'?Number(coupon.body.rateBps)/1000+'折':coupon.amount}}</text><text class="tiny">满{{coupon.threshold}}元可用</text></view><view class="coupon-copy"><text class="bold">{{coupon.title}}</text><text class="tiny muted">{{state.shop}} · 指定商品</text><text class="tiny muted">有效期至 {{new Date(Number(coupon.body.expiresAt)).toLocaleDateString()}}</text></view><button class="coupon-button">{{block.choose?(form.coupon===coupon.id?'已选择':'选择'):backend.coupons.some(c=>c.campaign_ref===coupon.id)?'已领取':'领取'}}</button></view></view>
  <view v-else-if="block.type==='messages'" class="card"><view v-for="(message,i) in messages" :key="i" class="message-item" @tap="$emit('action',message.target)"><view class="icon-tile"><Icon :name="message.icon"/></view><view class="flex-one"><view class="spread"><text class="bold">{{message.title}}</text><text class="tiny muted">{{message.time}}</text></view><text class="small muted">{{message.body}}</text></view><view v-if="!message.read" class="unread-dot"/></view></view>
  <view v-else-if="block.type==='poster'" class="card poster"><text class="eyebrow">禾序商贸 · 品质好生活</text><text class="poster-title">好物有序<br/>美好生活</text><view class="poster-image"><Photo asset="hero"/></view><view class="spread"><view><text class="bold">C 云代理邀您同行</text><text class="muted tiny">识别专属邀请二维码</text></view><view class="qr"><Photo asset="qr"/></view></view></view>
  <view v-else-if="block.type==='table'" class="card table-card"><text class="section-title">{{block.title}}</text><scroll-view scroll-x><view class="data-table"><view class="table-row table-head"><text v-for="head in block.heads" :key="head">{{head}}</text></view><view v-for="(row,i) in block.rows" :key="i" class="table-row"><template v-for="(cell,j) in row" :key="j"><input v-if="block.editKeys" :aria-label="block.heads[j]" :value="form[block.editKeys[j]]" :type="j?'digit':'text'" :disabled="block.disabledKeys?.includes(block.editKeys[j])" style="width:100%;font-size:inherit;text-align:center" @input="set(block.editKeys[j],$event.detail.value)"/><text v-else>{{cell}}</text></template></view></view></scroll-view></view>
  <view v-else-if="block.type==='sortable'" class="card"><view v-for="(item,i) in sortItems" :key="item" class="info-row"><text class="muted">☰</text><text class="flex-one">{{item}}</text><button class="mini-btn" :disabled="i===0" @tap="move(i,-1)">↑</button><button class="mini-btn" :disabled="i===sortItems.length-1" @tap="move(i,1)">↓</button></view></view>
  <view v-else-if="block.type==='settlement'" class="card"><text class="section-title">分账试算明细</text><view v-for="item in settlementRows" :key="item[0]" class="info-row"><text class="row-label">{{item[0]}}</text><text class="row-value green">{{item[1]}}</text></view></view>
  <view v-else-if="block.type==='orderList'" class="orders"><view v-for="o in visibleOrders" :key="o.id" class="card" @tap="selectOrder(o,!!block.management)"><view class="spread"><text class="small">{{o.id}}</text><text class="green">{{o.status}}</text></view><view v-for="line in o.items" :key="line.lineId" class="product-line inner"><view class="product-thumb"><Photo :asset="products.find(p=>p.id===line.id)?.asset||'stapler'"/></view><view class="product-copy"><text class="product-name">{{line.name}}</text><text class="muted small">{{products.find(p=>p.id===line.id)?.spec||''}} × {{line.qty}}</text><text class="price">¥{{money(line.unitPrice*line.qty)}}</text></view></view><view class="order-actions"><button v-if="o.rawStatus==='UNPAID'&&!block.management" class="mini-btn" @tap.stop="cancelOrder(o)">取消订单</button><button class="mini-btn" @tap.stop="openOrderAction(o)">{{block.management&&o.rawStatus==='PAID'?'去发货':o.rawStatus==='UNPAID'?'去付款':o.rawStatus==='SHIPPED'?'查看物流':'查看订单'}}</button></view></view><view v-if="!visibleOrders.length" class="empty-state"><Icon name="file" :size="48"/><text>暂无相关订单</text></view></view>
  <view v-else-if="block.type==='cases'" class="cases"><view v-for="r in visibleRefunds" :key="r.id" class="card" @tap="selectRefund(r)"><view class="spread"><text class="bold">{{refundTypes[r.refund_type]}} · {{r.member_id}}</text><text class="badge">{{refundStatuses[r.status]||r.status}}</text></view><view class="product-line inner"><view class="product-thumb"><Photo asset="stapler"/></view><view class="product-copy"><text>{{r.order_id}}</text><text class="muted small">{{r.reason}} · 申请数量{{r.qty}}件</text><text class="price">¥{{money(r.amount)}}</text></view></view><view class="spread"><text class="tiny muted">{{r.id}}</text><text class="green">查看详情 →</text></view></view></view>
</template>

<script setup>
import {computed,ref,watch} from 'vue'
import Icon from './Icon.vue'
import Photo from './Photo.vue'
import {products,money,state,toast} from '../data/store'
import {settlement} from '../data/business.mjs'
import {backend,apiCommand,refresh,selectOrder,selectRefund,uploadAttachment} from '../data/backend'
const props=defineProps({block:Object,form:Object,filter:String,search:String})
const emit=defineEmits(['action','update','filter','search'])
const set=(key,value)=>emit('update',key,value)
const tab=ref(0),query=ref(''),uploads=ref([]),claimed=ref([]);const sortItems=computed(()=>props.form.sortOrder||props.block.items||[])
watch(()=>props.form._catalogId,()=>{if(props.form._catalogId)uploads.value=[...(props.form.uploads||[])]},{immediate:true})
const prod=computed(()=>props.block.product||products.find(p=>p.id===props.block.id)||products[0])
const visibleItems=computed(()=>(props.block.items||[]).filter(x=>!props.search||x.join(' ').includes(props.search)))
const visibleProducts=computed(()=>{let p=(props.block.products||products).filter(p=>(props.block.ids||['cup','towel','umbrella','paper']).includes(p.id));if(props.block.type==='pointsProducts')p=p.filter(x=>Number(x.point_price)>0);if(props.search)p=p.filter(x=>x.name.includes(props.search));if(props.filter==='零库存')p=p.filter(x=>!x.stock);if(props.filter==='低库存')p=p.filter(x=>x.stock<50);return p})
const coupons=computed(()=>backend.coupons.filter(c=>props.block.choose?c.kind==='coupon_claim'&&c.status==='AVAILABLE':c.kind==='coupon').map(c=>({...c,amount:Number(c.body.discount)/100,threshold:Number(c.body.threshold)/100,title:c.body.name})))
const messages=computed(()=>state.notifications.map(x=>{const type=x.event||'SYSTEM',category=type.startsWith('ORDER_')?'订单':type==='REFUND_UPDATED'?'售后':type==='AGENT_UPDATED'?'代理':['WITHDRAW_UPDATED','POINTS_UPDATED'].includes(type)?'资金':'系统';return {title:x.message,body:x.body||x.message,category,icon:category==='资金'?'wallet':category==='订单'?'file':'bell',target:'message-open:'+x.id,read:x.read,time:new Date(x.time).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}}).filter(m=>!props.filter||props.filter==='全部'||m.category===props.filter))
const settlementRows=computed(()=>{if(props.block.items)return props.block.items;const s=settlement(Math.max(1,Number(props.form.quantity)||1),(Number(props.form.rate)||0)/100);return [['C1 零售毛利','¥'+money(s.retail)],['C 同级分红','¥'+money(s.peer)],['B 中心毛利','¥'+money(s.center)],['A 总代毛利','¥'+money(s.ownerGross)],['A 分红承担','−¥'+money(-s.ownerCost)],['A 实际净收益','¥'+money(s.ownerNet)]]})
function choose(){if(uploads.value.length>=9){toast('最多上传9张');return}uni.chooseImage({count:9-uploads.value.length,success:async r=>{const route=getCurrentPages().slice(-1)[0]?.route||'';const purpose=/M2[0-4]|G2[5-8]/.test(route)?'RETURN':route.includes('M10')?'REVIEW':route.includes('G10')?'PRODUCT':route.includes('G46')?'FINANCE':route.includes('G56')?'LINK_CONFIRMATION':'IDENTITY';for(const file of r.tempFilePaths){try{const uploaded=await uploadAttachment(file,purpose);uploads.value.push(file);set('uploads',[...(props.form.uploads||[]),uploaded.id])}catch(e){toast(e.message)}}},fail:()=>toast('未选择图片')})}
function removeUpload(i){uploads.value.splice(i,1);const ids=[...(props.form.uploads||[])];ids.splice(i,1);set('uploads',ids)}
async function selectCoupon(i){const c=coupons.value[i];if(props.block.choose){set('coupon',c.id)}else{try{await apiCommand('coupon-claim',{id:c.id});await refresh();toast('优惠券已领取')}catch(e){toast(e.message)}}}
function move(i,d){const a=[...sortItems.value];[a[i],a[i+d]]=[a[i+d],a[i]];set('sortOrder',a);set('categoryNames',a.join('\n'))}
const visibleOrders=computed(()=>(props.block.management?backend.management.G21||[]:state.orders).filter(o=>!props.filter||props.filter==='全部'||o.status===props.filter).filter(o=>!props.search||JSON.stringify(o).includes(props.search)))
const refundTypes={REFUND_ONLY:'仅退款',RETURN:'退货退款',PARTIAL:'部分退款',EXCHANGE:'换货'}
const refundStatuses={PENDING:'待审核',WAIT_RETURN:'待退货',APPROVED:'待渠道退款',SUCCESS:'已退款',CLOSED:'已关闭',EXCHANGE_SHIPPED:'换货已发出',WAIT_EXCHANGE:'待换货发出',REJECTED:'已驳回'}
const visibleRefunds=computed(()=>(backend.management.G25||[]).filter(r=>!props.filter||props.filter==='全部'||refundTypes[r.refund_type]===props.filter))
function openOrderAction(o){state[props.block.management?'managementOrder':'activeOrder']=o.id;if(!props.block.management)backend.activeOrder=o;emit('action',props.block.management?(o.rawStatus==='PAID'?'G23':'G22'):o.rawStatus==='UNPAID'?'M15':o.rawStatus==='SHIPPED'?'M19':'M18')}
async function cancelOrder(o){try{await apiCommand('order-cancel',{id:o.id});await refresh();toast('订单已取消')}catch(e){toast(e.message)}}
</script>
